language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chakatz/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true chakatz/react-test npm run test

after_success:
  - docker build -t chakatz/multi-client ./client
  - docker build -t chakatz/multi-nginx ./nginx
  - docker build -t chakatz/multi-server ./server
  - docker build -t chakatz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chakatz/multi-client
  - docker push chakatz/multi-nginx
  - docker push chakatz/multi-server
  - docker push chakatz/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "multi-docker"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-us-east-2-962766033217"
#  bucket_path: "multi-docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
